[package]
name = "frostore"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21"
bincode = "1"
dashmap = "5"
data-encoding = "2"
frost-ed25519 = "1.0.0-rc.0"
futures = "0.3"
libp2p = { version = "0.53", features = ["cbor", "gossipsub", "identify", "kad", "macros", "noise", "request-response", "tcp", "tokio", "yamux"] }
once_cell = "1"
rand = "0.8"
sha3 = "0.10"
tokio = { version = "1", features = ["full"] }
