[package]
name = "frostore"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
bincode = "1"
dashmap = "5"
data-encoding = "2"
frost-ed25519 = "0.7"
futures = "0.3"
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = ["gossipsub", "identify", "kad", "macros", "noise", "tcp", "tokio", "yamux"] }
once_cell = "1"
rand = "0.8"
sha3 = "0.10"
tokio = { version = "1", features = ["full"] }
